//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace AccountEx.CodeFirst.Models
{
    public partial class WheatPurchaseItem : BaseEntity
    {

        public int Id { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public int PartyId { get; set; }
        public int ItemId { get; set; }
        public string Party { get; set; }
        public string Item { get; set; }
        public int BillNo { get; set; }
        public int Bags { get; set; }
        public decimal StandardWeight { get; set; }
        public decimal BardanaWeight { get; set; }
        public string TruckNo { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal Khot { get; set; }
        public int BardanaReturned { get; set; }
        public int Freight { get; set; }
        public decimal BardanaRate { get; set; }
        public decimal WheatRate { get; set; }
        public decimal NetWeight { get; set; }
        public byte BardanaType { get; set; }
        public decimal Amount { get; set; }
       
    }
}
