//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name is required.
        /// </summary>
        internal static string AccountNameisrequired {
            get {
                return ResourceManager.GetString("AccountNameisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountStructure.
        /// </summary>
        internal static string AccountStructure {
            get {
                return ResourceManager.GetString("AccountStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        internal static string AddAccoun {
            get {
                return ResourceManager.GetString("AddAccoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit.
        /// </summary>
        internal static string AddEdit {
            get {
                return ResourceManager.GetString("AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parent Account.
        /// </summary>
        internal static string AddParentAccount {
            get {
                return ResourceManager.GetString("AddParentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Route Account.
        /// </summary>
        internal static string AddRouteAccount {
            get {
                return ResourceManager.GetString("AddRouteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Item In Current Voucher.
        /// </summary>
        internal static string AllItemInCurrentVoucher {
            get {
                return ResourceManager.GetString("AllItemInCurrentVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount is required.
        /// </summary>
        internal static string amountisrequired {
            get {
                return ResourceManager.GetString("amountisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Number.
        /// </summary>
        internal static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Number is required.
        /// </summary>
        internal static string BillNumberisrequired {
            get {
                return ResourceManager.GetString("BillNumberisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payments.
        /// </summary>
        internal static string CashPayments {
            get {
                return ResourceManager.GetString("CashPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Receipts.
        /// </summary>
        internal static string CashReceipts {
            get {
                return ResourceManager.GetString("CashReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challan.
        /// </summary>
        internal static string Challan {
            get {
                return ResourceManager.GetString("Challan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challan is required.
        /// </summary>
        internal static string Challanisrequired {
            get {
                return ResourceManager.GetString("Challanisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of Accounts.
        /// </summary>
        internal static string ChartofAccounts {
            get {
                return ResourceManager.GetString("ChartofAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required.
        /// </summary>
        internal static string Customerisrequired {
            get {
                return ResourceManager.GetString("Customerisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Ledger.
        /// </summary>
        internal static string DetailedLedger {
            get {
                return ResourceManager.GetString("DetailedLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailItem.
        /// </summary>
        internal static string DetailItem {
            get {
                return ResourceManager.GetString("DetailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare.
        /// </summary>
        internal static string Fare {
            get {
                return ResourceManager.GetString("Fare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        internal static string FromAccount {
            get {
                return ResourceManager.GetString("FromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        internal static string GeneralLedger {
            get {
                return ResourceManager.GetString("GeneralLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass Bikri.
        /// </summary>
        internal static string GrassBikri {
            get {
                return ResourceManager.GetString("GrassBikri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        internal static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is required.
        /// </summary>
        internal static string Itemisrequired {
            get {
                return ResourceManager.GetString("Itemisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour.
        /// </summary>
        internal static string Labour {
            get {
                return ResourceManager.GetString("Labour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Store.
        /// </summary>
        internal static string LabourStore {
            get {
                return ResourceManager.GetString("LabourStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laga.
        /// </summary>
        internal static string Laga {
            get {
                return ResourceManager.GetString("Laga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Purchase.
        /// </summary>
        internal static string ManagePurchase {
            get {
                return ResourceManager.GetString("ManagePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Sales.
        /// </summary>
        internal static string ManageSales {
            get {
                return ResourceManager.GetString("ManageSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka is Required.
        /// </summary>
        internal static string MarkaIsRequired {
            get {
                return ResourceManager.GetString("MarkaIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markeet Fee.
        /// </summary>
        internal static string MarkeetFee {
            get {
                return ResourceManager.GetString("MarkeetFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezaan.
        /// </summary>
        internal static string Mezaan {
            get {
                return ResourceManager.GetString("Mezaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munshyiana.
        /// </summary>
        internal static string Munshyiana {
            get {
                return ResourceManager.GetString("Munshyiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Sale.
        /// </summary>
        internal static string NetSale {
            get {
                return ResourceManager.GetString("NetSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        internal static string OpeningBalance {
            get {
                return ResourceManager.GetString("OpeningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Voucher.
        /// </summary>
        internal static string PendingVoucher {
            get {
                return ResourceManager.GetString("PendingVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Voucher Required.
        /// </summary>
        internal static string PendingVoucherRequired {
            get {
                return ResourceManager.GetString("PendingVoucherRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qty is required.
        /// </summary>
        internal static string qtyisrequired {
            get {
                return ResourceManager.GetString("qtyisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Total.
        /// </summary>
        internal static string QuantityTotal {
            get {
                return ResourceManager.GetString("QuantityTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate is required.
        /// </summary>
        internal static string rateisrequired {
            get {
                return ResourceManager.GetString("rateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Form/Report.
        /// </summary>
        internal static string RecoveryForm {
            get {
                return ResourceManager.GetString("RecoveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale date is required.
        /// </summary>
        internal static string Saledateisrequired {
            get {
                return ResourceManager.GetString("Saledateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Detail.
        /// </summary>
        internal static string SaleDetail {
            get {
                return ResourceManager.GetString("SaleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Ledger.
        /// </summary>
        internal static string SaleLedger {
            get {
                return ResourceManager.GetString("SaleLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Summary.
        /// </summary>
        internal static string SaleSummary {
            get {
                return ResourceManager.GetString("SaleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Type.
        /// </summary>
        internal static string SaleType {
            get {
                return ResourceManager.GetString("SaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Store Period.
        /// </summary>
        internal static string SelectStorePeriod {
            get {
                return ResourceManager.GetString("SelectStorePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Supplier.
        /// </summary>
        internal static string SelectSupplier {
            get {
                return ResourceManager.GetString("SelectSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Is Required.
        /// </summary>
        internal static string StoreIsRequired {
            get {
                return ResourceManager.GetString("StoreIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Purchase.
        /// </summary>
        internal static string StorePurchase {
            get {
                return ResourceManager.GetString("StorePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Rent.
        /// </summary>
        internal static string StoreRent {
            get {
                return ResourceManager.GetString("StoreRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier is required.
        /// </summary>
        internal static string Supplierisrequired {
            get {
                return ResourceManager.GetString("Supplierisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        internal static string ToAccount {
            get {
                return ResourceManager.GetString("ToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balance.
        /// </summary>
        internal static string TrialBalance {
            get {
                return ResourceManager.GetString("TrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Number is required.
        /// </summary>
        internal static string VehicleNumberisrequired {
            get {
                return ResourceManager.GetString("VehicleNumberisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher is required.
        /// </summary>
        internal static string Voucherisrequired {
            get {
                return ResourceManager.GetString("Voucherisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Number.
        /// </summary>
        internal static string VoucherNumber {
            get {
                return ResourceManager.GetString("VoucherNumber", resourceCulture);
            }
        }
    }
}
