//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MiscChargeItem: BaseEntity
    {
        public int VoucherNumber { get; set; }
        public int MiscChargeId { get; set; }
        public int TenantAccountId { get; set; }
        public string TenantAccountCode { get; set; }
        public string TenantAccountName { get; set; }
        public int ShopId { get; set; }
        public string ShopCode { get; set; }
        public string ShopNo { get; set; }
        public int ChargesAccountId { get; set; }
        public string ChargesAccountCode { get; set; }
        public string ChargesAccountName { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public Nullable <DateTime> Date { get; set; }
       
    }
}
