//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MiscCharge : BaseEntity
    {
        public MiscCharge()
        {
            this.MiscChargeItems = new HashSet<MiscChargeItem>();
        }
    
       
        public int VoucherNumber { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int FiscalId { get; set; }
    
        public virtual ICollection<MiscChargeItem> MiscChargeItems { get; set; }
    }
}
