//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OpeningBalance : BaseEntity
    {
        public int FiscalId { get; set; }
        public int AccountId { get; set; }
        public byte OpeningBalanceTypeId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Debit { get; set; }
        public decimal UnitPrice { get; set; }

        
        public decimal Credit { get; set; }
    }
}
