//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class RentDetailItem : BaseEntity
    {

        public int RentDetailId { get; set; }
        public int RentAgreementId { get; set; }
        public int ElectricityUnitItemId { get; set; }
        public int ElectricityUnitId { get; set; }
        public int VoucherNumber { get; set; }
        public int ShopId { get; set; }
        public string ShopNo { get; set; }
        public int TenantAccountId { get; set; }
        public string TenantAccountName { get; set; }
        public string TenantCode { get; set; }
        public decimal MonthlyRent { get; set; }
        public decimal UCPercent { get; set; }
        public decimal ElectricityCharges { get; set; }
        public decimal RentArrears { get; set; }
        public decimal UCPercentArears { get; set; }
        public decimal ElectricityArrears { get; set; }
        public decimal SurCharge { get; set; }
        public bool IsReceived { get; set; }
        public bool Status { get; set; }

        //public int FiscalId { get; set; }

    }
}
