//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Nexus
{
    using CodeFirst.Models;
    using System;
    using System.Collections.Generic;

    public partial class NexusPostedCasesItems : BaseEntity
    {
        public int PostedCaseId { get; set; }
        public Nullable<long> CaseDetailId { get; set; }
        public int TestId { get; set; }
        public string TestName { get; set; }
        public decimal Price { get; set; }
       
    }
}
