//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Nexus
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Serializable]
    public partial class Nexus_Vw_Cases
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long ID { get; set; }
        public string CaseNumber { get; set; }
        public long PatientID { get; set; }
        public string PatientName { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public string ReferenceName { get; set; }
        public Nullable<int> ConsultantID { get; set; }
        public string ConsultantName { get; set; }
        public int RegistrationLocation { get; set; }
        public int DestinationLocation { get; set; }
        public decimal TotalAmount { get; set; }
        public byte Discount { get; set; }
        public decimal Less { get; set; }
        public decimal NetAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public decimal Due { get; set; }
        public bool Completed { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> BankDueReceived { get; set; }
        public Nullable<decimal> BankPaid { get; set; }
        public Nullable<decimal> DueReceived { get; set; }
        public bool AlertSent { get; set; }

    }
}
