//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Nexus
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Serializable]
    public partial class Nexus_Test
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ReportName { get; set; }
        public string TestHeading { get; set; }
        public string ReportGroup { get; set; }
        public string Synonyms { get; set; }
        public short GroupID { get; set; }
        public byte Type { get; set; }
        public bool IsSpecial { get; set; }
        public Nullable<byte> TestDays { get; set; }
        public Nullable<byte> ReportDays { get; set; }
        public Nullable<short> SpecimenID { get; set; }
        public string SpecimenReqQuantity { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public decimal Rate { get; set; }
        public string Unit { get; set; }
        public Nullable<short> TemplateID { get; set; }
        public string Format { get; set; }
        public Nullable<decimal> CriticalValueLowerBound { get; set; }
        public Nullable<decimal> CriticalValueUpperBound { get; set; }
        public string Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Status { get; set; }
        public short TestType { get; set; }
        public string StabilityFrozen { get; set; }
        public string StabilityRefrigerated { get; set; }
        public string StabilityRoom { get; set; }
    
    }
}
