//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Nexus
{
    using CodeFirst.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NexusPostedCases : BaseEntity
    {
        public NexusPostedCases()
        {
            NexusPostedCasesItems = new HashSet<NexusPostedCasesItems>();
        }
        public int VoucherNumber { get; set; }
        public long CaseId { get; set; }
        public DateTime Date { get; set; }


        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Discount { get; set; }
        public decimal Less { get; set; }
        public decimal NetAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal Due { get; set; }
        public int FiscalId { get; set; }
        [ForeignKey("PostedCaseId")]
        public virtual ICollection<NexusPostedCasesItems> NexusPostedCasesItems { get; set; }

    }
}
