//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Nexus
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Serializable]
    public partial class Nexus_Patient
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FHName { get; set; }
        public byte Sex { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte MaritalStatus { get; set; }
        public string BloodGroup { get; set; }
        public string NIC { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public string PatientNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Status { get; set; }
        public int Location { get; set; }
        public string MedicalRecordNo { get; set; }
        public string CABGNo { get; set; }
    
    }
}
