//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CRMPMCItems
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Product { get; set; }
        public int CurrencyId { get; set; }
        public string Currency { get; set; }
        public decimal ExcRate { get; set; }
        public decimal Price { get; set; }
        public int AnnualQty { get; set; }
        public Nullable<decimal> AnnualPotential { get; set; }
        public bool IsAnnualRPLPotential { get; set; }
        public bool IsCounter { get; set; }
        public bool IsActive { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
