//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Vehicles
{
    using System;
    using System.Collections.Generic;

    public partial class BLCharge:BaseEntity
    {
        public int BLId { get; set; }
        public decimal Amount { get; set; }
        public int ChargeId { get; set; }
        public int SupplierId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ChassisNo { get; set; }
        public bool IsPaid { get; set; }
    }
}
