//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Vehicles
{
    using System;
    using System.Collections.Generic;

    public partial class UserVehicleBranch : BaseEntity
    {
        
        public int UserId { get; set; }
        public int BranchId { get; set; }
       
    }
}
