//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Vehicles
{
    using System;
    using System.Collections.Generic;

    public partial class VehicleAcution : BaseEntity
    {

        public int AcutionerId { get; set; }
        public int SaleId { get; set; }
        public int VehicleId { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
        public Nullable<System.DateTime> AuctionerFinalizationDate { get; set; }
        public Nullable<System.DateTime> RepossessedDate { get; set; }
        public string MailTo { get; set; }
        public int AdvertisementDays { get; set; }
        public int NotificationDays { get; set; }
        public Nullable<System.DateTime> AdvertisementDate { get; set; }
        public string Newspaper { get; set; }
        public decimal Charges { get; set; }
        public bool IsChargesFinalized { get; set; }
    }
}
