//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.Vehicles
{
    using System;
    using System.Collections.Generic;

    public partial class VehiclePenalty : BaseEntity
    {

        public int VehicleSaleId { get; set; }
        public int VehicleId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string PaymentMode { get; set; }
        public string ChequeNo { get; set; }
        public string Remarks { get; set; }
        public int VoucherNo { get; set; }
    }
}
