//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class RentOpeningBalance : BaseEntity
    {
        public int TenantAccountId { get; set; }
        public int VoucherNumber { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int RentAgreementId { get; set; }
        public int RentItemId { get; set; }
        public decimal Rent { get; set; }
        public decimal UC { get; set; }
        public decimal Electricity { get; set; }
        public decimal SurCharge { get; set; }
        public decimal NetAmount { get; set; }
        public int FiscalId { get; set; }
       
        

    }
}
