//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("vw_RentOpeningBalances")]
    public partial class vw_RentOpeningBalance
    {
        public int Id { get; set; }
        public int TenantAccountId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int RentAgreementId { get; set; }
        public string TenantAccountName { get; set; }
        public string Block { get; set; }
        public string ShopCode { get; set; }
        public string ShopNo { get; set; }
        public decimal Rent { get; set; }
        public decimal UC { get; set; }
        public decimal Electricity { get; set; }
        public decimal SurCharge { get; set; }
        public int FiscalId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CompanyId { get; set; }



    }
}
