//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRequisition:BaseEntity
    {
        public StockRequisition()
        {
            this.StockRequisitionItems = new HashSet<StockRequisitionItem>();
        }
        public int VoucherNumber { get; set; }
        public int FiscalId { get; set; }
        public System.DateTime Date { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DeliveryRequired { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }
        public string Instructions { get; set; }
     
        public virtual ICollection<StockRequisitionItem> StockRequisitionItems { get; set; }
        
    }
}
