//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class StockRequisitionItem : BaseEntity
    {
      
        public int StockRequisitionId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public int ItemId { get; set; }
        public int VoucherNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public string ArticleNo { get; set; }
       
        public string Unit { get; set; }
        public byte Status { get; set; }
        public decimal QuantityDelivered { get; set; }
        public Decimal? StockBalance { get; set; }
    }
}
