//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;
    using AccountEx.Common;
    
    public partial class SaleDiscount
    {

        public SaleDiscount()
        {
            SaleDiscountItems = new HashSet<SaleDiscountItem>();
           
        }
        public int Id { get; set; }
        public int InvoiceNumber { get; set; }
        public int VoucherNumber { get; set; }
        public VoucherType TransactionType { get; set; }
        public int QuantityTotal { get; set; }
        public decimal NetTotal { get; set; }
        public string Comments { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
        public int FiscalId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public virtual ICollection<SaleDiscountItem> SaleDiscountItems { get; set; }
    }
}
