//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using AccountEx.Common;

namespace AccountEx.CodeFirst.Models
{
    public partial class DCItem : BaseEntity
    {


        public int DeliveryChallanId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public int ItemId { get; set; }
        public int InvoiceNumber { get; set; }
        public string BatchNo { get; set; }
        public int RequisitionNo { get; set; }
        public int OrderNo { get; set; }
        public int VoucherNumber { get; set; }
        public int MainUnitQuantity { get; set; }
        public decimal Quantity { get; set; }
        public decimal NTQty { get; set; }
        public decimal QtyDelivered { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int WPNo { get; set; }
        public VoucherType TransactionType { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public string Unit { get; set; }
        //Article=ArticleNo from Products
        public string Article { get; set; }
        public decimal GSTPercent { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal Weight { get; set; }
        public decimal NetAmount { get; set; }
        public decimal Width { get; set; }
        public decimal Meters { get; set; }
        public decimal Rolls { get; set; }
        public decimal TotalMeters { get; set; }
        public decimal StandardWeight { get; set; }
        public string UnitType { get; set; }

    }
}
