//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OrderItem : BaseEntity
    {
        public int OrderId { get; set; }
        public int DcId { get; set; }
        public int DcNo { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemRemarks { get; set; }
        public int ItemId { get; set; }
        public byte EntryType { get; set; }
        public int InvoiceNumber { get; set; }
        public int VoucherNumber { get; set; }
        public decimal Quantity { get; set; }
        public decimal QtyDelivered { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public decimal PurchaseRate { get; set; }
        public string Unit { get; set; }
        public int Article { get; set; }
        public string ArticleNo { get; set; }
        public Nullable<decimal> GSTPercent { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public decimal NetAmount { get; set; }


    }
}
