//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;
    using AccountEx.Common;

    public partial class Order : BaseEntity
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderExpenseItems = new HashSet<OrderExpenseItem>();
        }

       
        public int AccountId { get; set; }
        public int ServiceSaleTaxNo { get; set; }
        public string AccountTitle { get; set; }
        public int InvoiceNumber { get; set; }
        public int VoucherNumber { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<int> ReceivingVoucher { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string PartyAddress { get; set; }
        public VoucherType TransactionType { get; set; }
        public decimal GrassTotal { get; set; }
        public int QuantityTotal { get; set; }
        public decimal Discount { get; set; }
        public decimal NetTotal { get; set; }
        public decimal MaterialConsumedTotal { get; set; }
        public string Comments { get; set; }
        public string BiltyNo { get; set; }
        public Nullable<System.DateTime> BiltyDate { get; set; }
        public string ShipVia { get; set; }
        public Nullable<int> ShipQty { get; set; }
        public string SaleType { get; set; }
        public System.DateTime Date { get; set; }
        public byte Status { get; set; }
        public int MachineId { get; set; }
        public string MachineCode { get; set; }
        public string MachineName { get; set; }
        //public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> OldId { get; set; }
        public Nullable<int> SalesmanId { get; set; }
        public string SalesmanName { get; set; }
        public string SalesmanCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public byte OrderType { get; set; }
        public int SRN { get; set; }
        public int FiscalId { get; set; }
        public string PartyPONumber { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string VendorRef { get; set; }
        public string Forwarder { get; set; }
        public string PaymentTerm { get; set; }
        public string ShippingMethod { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string ContactTime { get; set; }
        public string Problem { get; set; }
        public string ServicesRequired { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public int EmployeeId { get; set; }
        public string InitialObservation { get; set; }
        public string ServicesNeeded { get; set; }
        public string EstimatedTime { get; set; }
        public byte BehaviourLevel { get; set; }
        public byte ServicesLevel { get; set; }
        public string DelayTime { get; set; }
        public Nullable<decimal> PreviousReading { get; set; }
        public Nullable<decimal> CurrentReading { get; set; }
        public Nullable<decimal> Consumption { get; set; }
        public string SrNo { get; set; }
        public decimal ServiceNetTotal { get; set; }
        public decimal ExpensesTotal { get; set; }

        public string AirFilterCondition { get; set; }
        public string OilCondition { get; set; }
        public string Condition { get; set; }
        public int AuthLocationId { get; set; }

        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<OrderExpenseItem> OrderExpenseItems { get; set; }
    
    }
}
