//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OrderExpenseItem : BaseEntity
    {

        public int OrderId { get; set; }

        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeCode { get; set; }

        public Nullable<int> ExpenseId { get; set; }
        public string ExpenseCode { get; set; }
        public string ExpenseName { get; set; }
        public string PerformedBy { get; set; }
        public decimal Quantity { get; set; }
        public DateTime Date { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public decimal GSTPercent { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal NetAmount { get; set; }



    }
}
