//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;

    public partial class CalendarEvent : BaseEntity
    {
        public int VisitNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ModeId { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string GoogleCalendarEeventId { get; set; }
        public string GoogleCalendarEeventLink { get; set; }
        public int? FiscalId { get; set; }




    }
}
