//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using Common;
    using System;
    using System.Collections.Generic;

    public partial class CRMComplaint : BaseEntity
    {
        public CRMComplaint()
        {
            this.CRMComplaintFiles = new HashSet<CRMComplaintFile>();
        }

        public int RegionId { get; set; }
        public int VoucherNo { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ActualProductId { get; set; }
        public int PriorityId { get; set; }
        public string TestTypeId { get; set; }
        public string CounterProductIds { get; set; }
        public string Description { get; set; }
        public int LabId { get; set; }
        public CRMComplaintStatus StatusId { get; set; }
        public int AssignedToId { get; set; }
        public Nullable<int> ResolvedById { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<int> ClosedById { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public int FiscalId { get; set; }
        public virtual ICollection<CRMComplaintFile> CRMComplaintFiles { get; set; }

    }
}
