//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using Common;
    using System;
    using System.Collections.Generic;

    public partial class CRMImportGRN : BaseEntity
    {
        public Nullable<int> RequisitionId { get; set; }
        public System.DateTime Date { get; set; }
        public string PINumber { get; set; }
        public Nullable<System.DateTime> PIDate { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public int SRNo { get; set; }

        
        public int CurrencyId { get; set; }
        public decimal ExcRate { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public decimal NetTotal { get; set; }
        public string BLNo { get; set; }
        public Nullable<System.DateTime> BlDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public CRMSaleType SaleType { get; set; }
        public int SalePersonId { get; set; }
        public CRMSaleDeliveryType DeliveryType { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int FiscalId { get; set; }
        public string Remarks { get; set; }

    }
}
