//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using Common;
    using System;
    using System.Collections.Generic;

    public partial class CRMImportRequisition : BaseEntity
    {

        public CRMImportRequisition()
        {
            CRMImportRequisitionItems = new HashSet<CRMImportRequisitionItem>();

        }
        public CRMImportRequisitionStatus Status { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public int VoucherNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public int RevisionNo { get; set; }
        public Nullable<int> DeliveryTermId { get; set; }
        public Nullable<int> VesselId { get; set; }
        public Nullable<int> POLId { get; set; }
        public Nullable<int> PODId { get; set; }
        public Nullable<int> FinalDestinationId { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public int SupplierId { get; set; }
        public decimal GrossTotal { get; set; }
        public decimal QuantityTotal { get; set; }
        public decimal Tax { get; set; }
        public decimal Discount { get; set; }
        public decimal NetTotal { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ReviseDate { get; set; }
        public Nullable<int> RevisedBy { get; set; }
        public int FiscalId { get; set; }
        public virtual ICollection<CRMImportRequisitionItem> CRMImportRequisitionItems { get; set; }
    }
}
