//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;

    public partial class CRMProject : BaseEntity
    {
        public int VoucherNumber { get; set; }
        public int? PMCItemId { get; set; }
        public int CustomerId { get; set; }
        public int SalePersonId { get; set; }
        public int ProductId { get; set; }
        public int CurrencyId { get; set; }
        public decimal ExcRate { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public decimal Potential { get; set; }
        public decimal PotentialPercent { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> LostReasonId { get; set; }
        public string Remarks { get; set; }
        public DateTime Date { get; set; }
        public DateTime? FromDate { get; set; }
        public int FiscalId { get; set; }

    }
}
