//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMProduct : BaseEntity
    {
        public string Name { get; set; }
        public string HSCode { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SecCategoryId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> SubGroupId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string TDSFileUrl { get; set; }
        public string TDSFileName { get; set; }
        public string MSDSFileUrl { get; set; }
        public string MSDSFileName { get; set; }
        public bool IsOwnProduct { get; set; }
     
    }
}
