//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using Common;
    using System;
    using System.Collections.Generic;

    public partial class CRMSaleInvoice : BaseEntity
    {
        public CRMSaleInvoice()
        {
            CRMSaleInvoiceItems = new HashSet<CRMSaleInvoiceItem>();

        }

        public System.DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public int InvoiceNumber { get; set; }
        public int VoucherNumber { get; set; }
        public Nullable<int> OGPNo { get; set; }
        public CRMSaleDeliveryType DeliveryType { get; set; }
        public CRMInvoiceType SaleType { get; set; }
        public string Comments { get; set; }
        public decimal GrossTotal { get; set; }
        public decimal QuantityTotal { get; set; }
        public decimal Tax { get; set; }
        public decimal Discount { get; set; }
        public decimal NetTotal { get; set; }
        public int FiscalId { get; set; }
        public virtual ICollection<CRMSaleInvoiceItem> CRMSaleInvoiceItems { get; set; }

    }
}
