//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;

    public partial class CRMSaleForecast : BaseEntity
    {
        public int ForecaseMonth { get; set; }
        public int ForecastYear { get; set; }
        public Nullable<int> SalePersonId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int ProductId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal Amount { get; set; }
        public decimal Quantity { get; set; }
        public byte Type { get; set; }
        public int FiscalId { get; set; }
        public string Remarks { get; set; }

    }
}
