//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using Common;
    using System;
    using System.Collections.Generic;

    public partial class CRMVendor : BaseEntity
    {

        public CRMVendorType Type { get; set; }
        public string Name { get; set; }

        
        public string ContactPerson { get; set; }

        public string Supplier { get; set; }
        public string CellNo { get; set; }
       
        public string Email { get; set; }
        

        public string Fax { get; set; }
        public string Web { get; set; }
        public string NTN { get; set; }

        public string Address { get; set; }
       
      
    }
}
