//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;

    public partial class PMC : BaseEntity
    {

        public PMC()
        {
            PMCItems = new HashSet<PMCItem>();
        }
        public int VoucherNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public int CustomerId { get; set; }
        public int SalePersonId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RegionId { get; set; }
        public DateTime Date { get; set; }
        public int FiscalId { get; set; }
        public virtual ICollection<PMCItem> PMCItems { get; set; }

    }
}
