//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMCItem : BaseEntity
    {
        public int PMCId { get; set; }
        public int SalePersonId { get; set; }
        public int SN { get; set; }
        public int ProductId { get; set; }
        public int CurrencyId { get; set; }
        public decimal ExcRate { get; set; }
        public decimal Price { get; set; }
        public decimal AnnualQty { get; set; }
        public Nullable<decimal> AnnualPotential { get; set; }
        public decimal AnnualRPLPotential { get; set; }
        public bool IsAnnualRPLPotential { get; set; }
        public bool IsCounter { get; set; }
        public bool IsActive { get; set; }
      
    }
}
