//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("vw_CRMUsers")]
    public partial class vw_CRMUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CellNo { get; set; }
        public string OfficeNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> DomainId { get; set; }
        public string Domain { get; set; }
        public Nullable<CRMUserType> UserTypeId { get; set; }
        public string UserType { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string Division { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Region { get; set; }
        public Nullable<int> RSMId { get; set; }
        public string RSM { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
