//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CRMPMCItems
    {
        public int Id { get; set; }
        public int PmcId { get; set; }
        public int VoucherNumber { get; set; }
        
        public int CustomerId { get; set; }
        public string Customer { get; set; }
        public int RegionId { get; set; }
        public int SalePersonId { get; set; }
        public string SalePerson { get; set; }
        public string Vendor { get; set; }
        public int SN { get; set; }
        public int ProductId { get; set; }
        public string Product { get; set; }
        public int DivisionId { get; set; }
        public string Division { get; set; }
        public int CurrencyId { get; set; }
        public string Currency { get; set; }
        public decimal ExcRate { get; set; }
        public decimal Price { get; set; }
        public decimal AnnualQty { get; set; }
        public Nullable<decimal> AnnualPotential { get; set; }
        public decimal AnnualRPLPotential { get; set; }
        public string IsCounter { get; set; }
        public string IsActive { get; set; }
        public string Project { get; set; }
        public int CompanyId { get; set; }
        public int FiscalId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
