//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CRMImportIGRN
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public string Customer { get; set; }
        public string InvoiceNo { get; set; }
        public string PINumber { get; set; }
        public Nullable<System.DateTime> PIDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string BLNo { get; set; }
        public Nullable<System.DateTime> BlDate { get; set; }
        public int ProductId { get; set; }
        public string Product { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string Currency { get; set; }
        public decimal ExcRate { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public decimal NetTotalF { get; set; }
        public decimal NetTotal { get; set; }
        public string SaleType { get; set; }
        public string Project { get; set; }
        public string SalePerson { get; set; }
        public int SalePersonId { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<int> RegionId { get; set; }
        public bool IsDeleted { get; set; }
        public int FiscalId { get; set; }
        public int CompanyId { get; set; }
    }
}
