//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("vw_CRMImportRequisitions")]
    public partial class vw_CRMImportRequisition
    {

        public int Id { get; set; }
        public CRMImportRequisitionStatus Status { get; set; }
        public string ImportStatus { get; set; }

        
        public System.DateTime Date { get; set; }
        public string Customer { get; set; }
        public int CustomerId { get; set; }
        public int RegionId { get; set; }

        
        public string CustomerNTN { get; set; }
        public string PINumber { get; set; }
        public int VoucherNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public string DeliveryTerm { get; set; }
        public string Vessel { get; set; }
        public string POL { get; set; }
        public string POD { get; set; }
        public string FinalDestination { get; set; }
        public string ContractType { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public string Supplier { get; set; }
        public int SupplierId { get; set; }
        public decimal GrossTotal { get; set; }
        public decimal QuantityTotal { get; set; }
        public decimal Tax { get; set; }
        public decimal Discount { get; set; }
        public decimal NetTotal { get; set; }
        public virtual int CreatedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ReviseDate { get; set; }
        public Nullable<int> RevisedBy { get; set; }
        public int FiscalId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
