//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;

    public partial class vw_CRMProjects
    {
        public int Id { get; set; }
        public int VoucherNumber { get; set; }
        public int PMCItemId { get; set; }
        public DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public int RegionId { get; set; }
        public int DivisionId { get; set; }
        public int SalePersonId { get; set; }
        public string Customer { get; set; }
        public int ProductId { get; set; }
        public string Product { get; set; }
        public string Division { get; set; }
        public Nullable<int> ActualProductId { get; set; }
        public string ActualProduct { get; set; }
        public string ActualProductDivision { get; set; }
        public string ActualProductVendor { get; set; }
        public int CurrencyId { get; set; }
        public string Currency { get; set; }
        public string ActualCurrency { get; set; }
        public decimal ExcRate { get; set; }
        public decimal ActualPrice { get; set; }
        public decimal Price { get; set; }
        public decimal ActualQuantity { get; set; }
        public decimal Quantity { get; set; }
        public decimal ActualPotential { get; set; }
        public decimal Potential { get; set; }
        public decimal PotentialPercent { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Status { get; set; }
        public int FiscalId { get; set; }
        public int CompanyId { get; set; }


        public bool IsDeleted { get; set; }
    }
}
