//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CRMPMCS
    {
        public int Id { get; set; }
        public int VoucherNumber { get; set; }
        public DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public string Customer { get; set; }
        public int SalePersonId { get; set; }
        public string SalePerson { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
