//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;

    public partial class WidgetParameter
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }
        public int WidgetId { get; set; }
        public string Name { get; set; }
        public string DisplayLabel { get; set; }
        public string Type { get; set; }
        public string InplutCssClass { get; set; }
        public string Value { get; set; }
        public byte AdvanceType { get; set; }
        public bool IsVisible { get; set; }
        public string ControlType { get; set; }
        public string Key { get; set; }
        public string JSFucntion { get; set; }
        public int SequenceNumber { get; set; }
    }
}
