//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountEx.CodeFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Widget
    {
        public Widget()
        {
            WidgetColumns = new HashSet<WidgetColumn>();
            WidgetParameters = new HashSet<WidgetParameter>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string WidgetName { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public bool ShowFooter { get; set; }
        public bool ShowFirstRow { get; set; }
        public bool GraphEnabled { get; set; }
        public string GraphFucntion { get; set; }
        public bool DirectRun { get; set; }
        public int CategoryIndex { get; set; }
        public int LegendStart { get; set; }
        public int HeaderEnd { get; set; }
        public int HeaderStart { get; set; }
        public int LegendEnd { get; set; }
        public string SkipHeaders { get; set; }
        public string SkipLegends { get; set; }
        public int SequenceNumber { get; set; }
        public string JsFunction { get; set; }
        public string Template { get; set; }
        public bool IsExternal { get; set; }
        public bool IsExecuted { get; set; }
        public bool IsTileWidget { get; set; }
        public bool IsReloadRequired { get; set; }
        public byte GraphType { get; set; }
        public int Radius { get; set; }
        public int Right { get; set; }
        public int Top { get; set; }
        public virtual ICollection<WidgetColumn> WidgetColumns { get; set; }
        public virtual ICollection<WidgetParameter> WidgetParameters { get; set; }

    }
}
